apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-app-deployment
  labels:
    app: expense-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-app
  template:
    metadata:
      labels:
        app: expense-app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: expense-app
          image: lokesh86186/react:latest
          ports:
            - containerPort: 80
              
        