apiVersion: v1
kind: Service
metadata:
  name: expense-app-service
spec:
  type: NodePort
  selector:
    app: expense-app
  ports:
    - protocol: TCP
      port: 80            # Service port inside cluster
      targetPort: 80